<?php
/**
 * Product view templates
 *
 * @var \Magento\Catalog\Block\Product\View $block
 * @var \Magento\Framework\Escaper $escaper
 * @var \Elogic\Internship\ViewModel\ProductStoreStockViewModel $storesViewModel
 */
?>
<?php
$_product = $block->getProduct();
$productStores = $_product->getData("store_in_stock");
$storesList = explode(",", $productStores);
$storesViewModel = $block->getData('view_model');
?>

<?php if ($productStores && $storesViewModel->getStoreNameById((int)$storesList["0"]) !== null): ?>
    <div class="product-store-stock-title">
    <span>
        <?= $escaper->escapeHTML(__('Available in stores: ')) ?>
    </span>
    </div>
    <div class="store-product-stock">
        <?php foreach ($storesList as $storeId): ?>
            <div class="product-store-stock">
                <?= $storesViewModel->getStoreNameById((int)$storeId) ?>
            </div>
        <?php endforeach; ?>
    </div>
<?php endif; ?>
