<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var \Elogic\Directory\Block\Adminhtml\GeoDB\System\Config\TestConnection $block */
/** @var \Magento\Framework\Escaper $escaper */
?>
<div data-bind="scope: 'elogic-geodb-test-connection'" class="scalable" style="text-align: center;">
    <!-- ko template: getTemplate() --><!-- /ko -->
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "elogic-geodb-test-connection": {
                        "component": "Elogic_Directory/js/geodb/connection",
                        "success": "<?= $escaper->escapeHtmlAttr($block->isConnectionSuccessful()) ?>",
                        "url": "<?= $escaper->escapeJs($escaper->escapeUrl($block->getAjaxUrl())) ?>",
                        "buttonLabel": "<?= $escaper->escapeHtml($block->getButtonLabel()) ?>"
                    }
                }
            }
        }
    }
</script>
